### ISSUE TITLE
Error at pair

### ISSUE THREAD

**Issue by newmax1** [Athou/moonlight-openelec-raspberrypi2#1]
Hi.

When i tried to pair i have error:

OpenELEC:~/moonlight # LD_LIBRARY_PATH='pwd'/lib:$LD_LIBRARY_PATH ./moonlight pair 192.168.0.132
./moonlight: error while loading shared libraries: libgamestream.so.0: cannot open shared object file: No such file or directory

i inspect lib folder and there is on file named libgamestream.so.0

I have the folder "moonlight" in storage folder.

What's happen?

Thank you!!

**Comment by Athou** [comment]
You have to use the ` character instead of ' around pwd.
Did you copy paste the command or did you type it back ?

**Comment by newmax1** [comment]
Yes! i tried firts 

OpenELEC:~/moonlight # LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH ./moonlight pair 192.168.0.132
Illegal instruction

But as you can see it return "Illegal instruction" for this i changed ` for '

Thanks!

**Comment by Athou** [comment]
could you try this ?

    LD_LIBRARY_PATH=/storage/moonlight/lib:$LD_LIBRARY_PATH ./moonlight pair 192.168.0.132

**Comment by newmax1** [comment]
Sorry.but is the same

OpenELEC:~/moonlight # LD_LIBRARY_PATH=/storage/moonlight/lib:$LD_LIBRARY_PATH ./moonlight pair 192.168.0.132
Illegal instruction

**Comment by Athou** [comment]
What version of openelec are you on?

**Comment by newmax1** [comment]
5.0.5

**Comment by Athou** [comment]
I can't reproduce your issue, but I only tested this on openelec 6.0.1.
Upgrading may or may not fix the issue.

**Comment by newmax1** [comment]
Ok. Actually i can't updagre. 

Thank you very much for your support.

**Comment by Athou** [comment]
Does the last commit help by any chance?

**Comment by newmax1** [comment]
Hi! first of all.  thanks for your work!

But it's not help. "Illegal instruction"

Maybe is that my raspberry is raspberry 1 model B??

**Comment by Athou** [comment]
Yes that's it, I use the armv7 libraries and I think the pi1 is not compatible.

**Comment by newmax1** [comment]
Ok, I'll try on raspbian.

Thanks for your attention, support and work!
